name: versioning
description: A Flutter package to check app version on startup. It requires a Firebase Database.
version: 1.0.0
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^3.0.8
  package_info: ^0.4.0+6
  launch_review: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


# The following section is specific to Flutter.
flutter:

