name: versioning
description: A Flutter package to check app version on startup. It requires a Firebase Database.
version: 1.2.0
homepage:

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  dio: ^4.0.0
  package_info: 
  launch_review: 
  shared_preferences: 
  provider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


# The following section is specific to Flutter.
flutter:

